version: "3"

services:
  redis-spring-boot:
    image: redis:alpine
    ports:
      - 6380:6379
    tty: true

  postgresql:
    image: postgres
    volumes:
      - postgresql:/data/postgresql
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    restart: unless-stopped

  keycloak:
    image: jboss/keycloak:16.1.0
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgresql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: 123456
    ports:
      - 8082:8080  # pc-port : docker-port, only change first port
    depends_on:
      - postgresql

volumes:
  postgresql: